import Provider from '@/components/Provider';

import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <main className="p-24">{children}</main>
        </body>
      </Provider>
    </html>
  );
}
